apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: django
  name: django
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: django
status:
  loadBalancer: {}