# Generated by Django 3.2.15 on 2022-08-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='age',
            field=models.IntegerField(),
        ),
    ]
