# Generated by Django 3.2.15 on 2022-08-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_alter_database_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
