version: '3.3'

services:
   db-svc:
    image: postgres
    volumes:
       - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 0.0.0.0:5432:5432

   app-server:
    depends_on:
      - db-svc
    image: ajais/django:v1
    #command: sleep 1000000
    ports:
      - 0.0.0.0:8000:8000

volumes:
    db_data: {}
