version: '3.3'

services:
   db-svc:
    image: postgres
    volumes:
       - db_data:/var/lib/postgresql/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 0.0.0.0:5432:5432

volumes:
    db_data: {}
